# deep-reasoning MCP shim, version 1. Generated by the Library; grant and update it in the Tools tab.
"""One MCP server as a deep_reasoner tool (factory_from this file, factory mcp_server).

Only the standard library is imported here at module level: this file is also run as a
script (the guard), and is stored in the Library as every grant's source. `mcp` and
deep_reasoner are imported where they are used.

In a dr-acp worker the factory hands over what the worker connected (SESSION); anywhere
else (plain dr, an export) it connects the server itself, from the block's snapshot and
the environment's values.
"""

import asyncio
import concurrent.futures
import contextlib
import keyword
import os
import re
import signal
import subprocess
import sys
import threading
import time
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import timedelta
from typing import Any, Final, Literal, NoReturn, TextIO

SHIM_VERSION: Final = 1
FACTORY: Final = "mcp_server"
CONNECT_TIMEOUT_S: Final = 10.0
CALL_TIMEOUT_S: Final = 120.0
CALL_GRACE_S: Final = 5.0  # past mcp's own read timeout, the call is given up here
GUARD_POLL_S: Final = 0.5
DESCRIPTION_LIMIT: Final = 300
RESULT_KEY: Final = "result"
HTTP_TIMEOUT_S: Final = 30.0  # mcp's own defaults for its HTTP client
HTTP_READ_TIMEOUT_S: Final = 300.0
REQUEST_TIMEOUT: Final = 408  # the code mcp's McpError carries for a read timeout
CONNECTION_CLOSED: Final = -32000  # mcp.types.CONNECTION_CLOSED
JSON_TYPES: Final = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
    "array": "list",
    "object": "dict",
    "null": "None",
}

UNAVAILABLE: Final = "{name} is not available in this conversation: {reason}."
NO_ANSWER: Final = (
    "its MCP server did not answer within {seconds:g} s when the conversation started"
)
COULD_NOT_START: Final = "its MCP server could not be started ({detail})"
MISSING_ENV: Final = "; not set in the environment: {names}"
NOT_ENABLED: Final = "its MCP server is not enabled in this app's MCP settings"
NOT_REACHED: Final = "no namespace this conversation can reach is granted it"
NOT_IN_SESSION: Final = "it was not connected when this conversation started"
NO_MCP_PACKAGE: Final = "the mcp package is not installed (pip install mcp)"
CALL_FAILED: Final = "{name}.{tool} failed: {text}"
CALL_TIMEOUT: Final = "{name}.{tool} did not answer within {seconds:g} s"
SERVER_STOPPED: Final = (
    "MCP server '{server}' stopped ({detail}); {name} is unavailable for the rest of "
    "this run."
)
HANDOFF_REFUSED: Final = (
    "MCP server '{server}' is granted to {granted}, not to '{dst}', so {name} cannot be "
    "handed to a sub-agent there. Grant it to '{dst}' in the Library's Tools tab."
)
DESCRIPTION_HEAD: Final = (
    "MCP server '{server}' ({transport}): call a tool as {name}.<tool>(…) or "
    '{name}("<tool name>", **arguments); a failed call raises McpToolError.'
)

# Set by dr-acp's worker (deep_reasoning.mcp.session) before tools are built: bound name -> Func.
SESSION: "dict[str, Any] | None" = None


class McpToolError(Exception):
    """A call that failed, timed out, or reached a server that is gone or was never bound."""


@dataclass(frozen=True)
class ServerSpec:
    name: str
    transport: Literal["stdio", "http", "sse"]
    command: str | None
    args: tuple[str, ...]
    env: Mapping[str, str]
    url: str | None
    headers: Mapping[str, str]


def _innermost(exc: BaseException) -> str:
    """'Type: message' of the first exception at the bottom of any exception groups."""
    while isinstance(exc, BaseExceptionGroup) and exc.exceptions:
        exc = exc.exceptions[0]
    return f"{type(exc).__name__}: {exc}"


def _parameters(tool: Any) -> tuple[list[str], list[str]]:
    """A tool's required parameters, then its others, each in the schema's order."""
    schema = tool.inputSchema or {}
    names = list(schema.get("properties") or {})
    required = set(schema.get("required") or ())
    return [n for n in names if n in required], [n for n in names if n not in required]


def _wrapped(tool: Any) -> bool:
    """The Python SDK's wrapper: an outputSchema whose only property is `result`."""
    return set((tool.outputSchema or {}).get("properties") or {}) == {RESULT_KEY}


def _attribute(tool_name: str) -> str | None:
    """The attribute a tool is reached by: its name with every character that cannot be
    in a Python name as "_", when that is an identifier and not a keyword."""
    attribute = re.sub(r"\W", "_", tool_name)
    if attribute.isidentifier() and not keyword.iskeyword(attribute):
        return attribute
    return None


async def _every_tool(session: Any) -> tuple[Any, ...]:
    """Every page of tools/list."""
    from mcp.types import PaginatedRequestParams

    page = await session.list_tools()
    tools = list(page.tools)
    while page.nextCursor:
        page = await session.list_tools(
            params=PaginatedRequestParams(cursor=page.nextCursor)
        )
        tools += page.tools
    return tuple(tools)


class Connection:
    """One server on a daemon thread running its own event loop (§4.3)."""

    failure: str | None
    tools: tuple[Any, ...]  # mcp.types.Tool

    def __init__(
        self,
        spec: ServerSpec,
        *,
        errlog: TextIO,
        call_timeout_s: float = CALL_TIMEOUT_S,
        name: str | None = None,
    ) -> None:
        self.spec = spec
        self.name = name or spec.name  # the REPL name its sentences use
        self.failure = None
        self.tools = ()
        self._errlog = errlog
        self._call_timeout_s = call_timeout_s
        self._ready = threading.Event()
        self._loop = asyncio.new_event_loop()
        self._task: asyncio.Task[None] | None = None
        self._session: Any = None
        self._gone: str | None = None  # why the server stopped answering, once it has

    def start(self) -> None:
        self._task = self._loop.create_task(self._serve())
        thread = threading.Thread(
            target=self._run, name=f"mcp-{self.name}", daemon=True
        )
        thread.start()

    def _run(self) -> None:
        asyncio.set_event_loop(self._loop)
        self._loop.run_until_complete(self._task)
        self._loop.close()

    def _transport(self) -> Any:
        """The mcp client transport for the spec: stdio through the guard, or HTTP/SSE."""
        spec = self.spec
        if spec.transport == "stdio":
            from mcp import StdioServerParameters
            from mcp.client.stdio import stdio_client

            guarded = ["-I", os.path.abspath(__file__), "--guard", "--"]
            server = StdioServerParameters(
                command=sys.executable,
                args=[*guarded, spec.command, *spec.args],
                env=dict(spec.env),
            )
            return stdio_client(server, errlog=self._errlog)
        if spec.transport == "sse":
            from mcp.client.sse import sse_client

            return sse_client(spec.url, headers=dict(spec.headers))
        import httpx
        from mcp.client.streamable_http import streamable_http_client

        @contextlib.asynccontextmanager
        async def streams() -> Any:
            timeout = httpx.Timeout(HTTP_TIMEOUT_S, read=HTTP_READ_TIMEOUT_S)
            client = httpx.AsyncClient(headers=dict(spec.headers), timeout=timeout)
            async with (
                client,
                streamable_http_client(spec.url, http_client=client) as s,
            ):
                yield s

        return streams()

    async def _serve(self) -> None:
        from mcp import ClientSession

        try:
            async with (
                self._transport() as streams,
                ClientSession(streams[0], streams[1]) as session,
            ):
                await session.initialize()
                self.tools, self._session = await _every_tool(session), session
                self._ready.set()
                await asyncio.Event().wait()  # until abandon() cancels this task
        except BaseException as exc:  # noqa: BLE001 -- the failure is what is reported
            self.failure = _innermost(exc)
        finally:
            if self._session is not None:
                self._gone = self._gone or self.failure
            self._ready.set()

    def wait_ready(self, timeout_s: float) -> bool:
        return self._ready.wait(max(0.0, timeout_s))

    def abandon(self) -> None:
        if self._task is not None and not self._loop.is_closed():
            with contextlib.suppress(RuntimeError):
                self._loop.call_soon_threadsafe(self._task.cancel)

    def _stopped(self) -> McpToolError:
        detail = self._gone or self.failure or "it was never started"
        return McpToolError(
            SERVER_STOPPED.format(server=self.spec.name, detail=detail, name=self.name)
        )

    def _failed(self, tool: str, text: str) -> McpToolError:
        return McpToolError(CALL_FAILED.format(name=self.name, tool=tool, text=text))

    def call(self, tool: str, arguments: Mapping[str, Any]) -> Any:
        """§8.3's result, or McpToolError; marks the connection dead when the server is gone."""
        import anyio
        from mcp.shared.exceptions import McpError

        if self._gone is not None or self._session is None:
            raise self._stopped()
        timeout = timedelta(seconds=self._call_timeout_s)
        sent = self._session.call_tool(
            tool, dict(arguments), read_timeout_seconds=timeout
        )
        future = asyncio.run_coroutine_threadsafe(sent, self._loop)
        timed_out = McpToolError(
            CALL_TIMEOUT.format(name=self.name, tool=tool, seconds=self._call_timeout_s)
        )
        try:
            result = future.result(self._call_timeout_s + CALL_GRACE_S)
        except concurrent.futures.TimeoutError:
            future.cancel()
            raise timed_out from None
        except McpError as exc:
            if exc.error.code == REQUEST_TIMEOUT:
                raise timed_out from None
            if exc.error.code == CONNECTION_CLOSED:
                self._gone = _innermost(exc)
                raise self._stopped() from None
            raise self._failed(tool, str(exc)) from None
        except (
            anyio.ClosedResourceError,
            anyio.BrokenResourceError,
            anyio.EndOfStream,
        ):
            self._gone = self._gone or self.failure or "the connection closed"
            raise self._stopped() from None
        except Exception as exc:  # noqa: BLE001 -- the call's failure goes to the cell
            raise self._failed(tool, _innermost(exc)) from None
        return self._result(tool, result)

    def _result(self, tool: str, result: Any) -> Any:
        """§8.3: the error raised, the SDK's wrapper unwrapped, a dict, text or blocks."""
        texts = [block.text for block in result.content if block.type == "text"]
        if result.isError:
            raise self._failed(tool, "\n".join(texts))
        structured = result.structuredContent
        if structured is not None:
            described = next((t for t in self.tools if t.name == tool), None)
            if described and _wrapped(described) and set(structured) == {RESULT_KEY}:
                return structured[RESULT_KEY]
            return structured
        if len(texts) == len(result.content):
            return "\n".join(texts)
        return [block.model_dump(mode="json") for block in result.content]


class McpTool:
    def __init__(self, server: "Server", tool: Any) -> None:
        self._server = server
        self._tool = tool
        self.__name__ = tool.name
        self.__doc__ = tool.description

    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        required, optional = _parameters(self._tool)
        ordered = [*required, *optional]
        if len(args) > len(ordered):
            raise TypeError(
                f"{self._server.__name__}.{self._tool.name} takes at most "
                f"{len(ordered)} positional arguments ({len(args)} given)"
            )
        arguments = dict(zip(ordered, args, strict=False)) | kwargs
        return self._server._connection.call(self._tool.name, arguments)

    def __cross_namespace__(self, src: str | None, dst: str) -> "McpTool":
        self._server.__cross_namespace__(src, dst)
        return self

    def __copy__(self) -> "McpTool":
        return self

    def __deepcopy__(self, memo: dict[int, Any]) -> "McpTool":
        return self


class Server:
    """What the REPL binds: callable by a tool's exact name, with one McpTool attribute per
    tool whose name makes a Python identifier."""

    __name__: str

    def __init__(
        self,
        name: str,
        connection: Connection,
        *,
        granted: frozenset[str] | None,
    ) -> None:
        self.__name__ = name
        self._connection = connection
        self._granted = granted
        for tool in connection.tools:
            attribute = _attribute(tool.name)
            if attribute and not hasattr(self, attribute):
                setattr(self, attribute, McpTool(self, tool))

    # Unannotated: deep_reasoner tells the agent this signature, `name(tool, /, **arguments)`.
    def __call__(self, tool, /, **arguments):
        return self._connection.call(tool, arguments)

    def __cross_namespace__(self, src: str | None, dst: str) -> "Server":
        """With granted set: PermissionError (HANDOFF_REFUSED) for a hand-off outside it."""
        if src is None or self._granted is None or dst in self._granted:
            return self
        raise PermissionError(
            HANDOFF_REFUSED.format(
                server=self._connection.spec.name,
                granted=", ".join(sorted(self._granted)),
                dst=dst,
                name=self.__name__,
            )
        )

    def __copy__(self) -> "Server":
        return self

    def __deepcopy__(self, memo: dict[int, Any]) -> "Server":
        return self


class Unavailable:
    """The stand-in for a server that is not bound: every call says why."""

    def __init__(self, name: str, reason: str) -> None:
        self.__name__ = name
        self._sentence = UNAVAILABLE.format(name=name, reason=reason)

    # Unannotated, as Server.__call__: the agent is told `name(*args, **kwargs)`.
    def __call__(self, *args, **kwargs):
        raise McpToolError(self._sentence)

    def __getattr__(self, attr: str) -> NoReturn:
        # Python's and deep_reasoner's own lookups (__cross_namespace__, __wrapped__,
        # inspect's _partialmethod, …) must find nothing, as on any plain object.
        if attr.startswith("_"):
            raise AttributeError(attr)
        raise McpToolError(self._sentence)

    def __copy__(self) -> "Unavailable":
        return self

    def __deepcopy__(self, memo: dict[int, Any]) -> "Unavailable":
        return self


def _type(schema: Mapping[str, Any]) -> str:
    declared = schema.get("type")
    if isinstance(declared, list):
        return " | ".join(JSON_TYPES.get(t, "Any") for t in declared)
    return JSON_TYPES.get(declared, "Any") if declared else "Any"


def _signature(name: str, tool: Any) -> str:
    """'  name.tool(a: str, b: int = …) -> str' (§8.4); the exact name in quotes when the
    tool has no attribute."""
    required, optional = _parameters(tool)
    properties = (tool.inputSchema or {}).get("properties") or {}
    params = [f"{p}: {_type(properties[p])}" for p in required]
    params += [f"{p}: {_type(properties[p])} = …" for p in optional]
    attribute = _attribute(tool.name)
    if attribute:
        call = f"{name}.{attribute}({', '.join(params)})"
    else:
        call = f'{name}("{tool.name}"{"".join(f", {p}" for p in params)})'
    if tool.outputSchema is None:
        returns = "str"
    elif _wrapped(tool):
        returns = _type(tool.outputSchema["properties"][RESULT_KEY])
    else:
        returns = "dict"
    return f"  {call} -> {returns}"


def describe(name: str, spec: ServerSpec, tools: Sequence[Any]) -> str:
    """§8.4's description."""
    head = DESCRIPTION_HEAD.format(
        server=spec.name, transport=spec.transport, name=name
    )
    lines = [head]
    for tool in tools:
        lines.append(_signature(name, tool))
        first = (tool.description or "").strip().split("\n", 1)[0].strip()
        if first:
            lines.append(f"    {first[:DESCRIPTION_LIMIT]}")
    return "\n".join(lines)


def bound(name: str, connection: Connection, *, granted: frozenset[str] | None) -> Any:
    """Func(Server(...), describe(...))."""
    from deep_reasoner.primitives import Func

    server = Server(name, connection, granted=granted)
    return Func(server, describe(name, connection.spec, connection.tools))


def unavailable(name: str, reason: str) -> Any:
    """Func(Unavailable(name, reason), UNAVAILABLE)."""
    from deep_reasoner.primitives import Func

    return Func(Unavailable(name, reason), UNAVAILABLE.format(name=name, reason=reason))


def spec_from_block(
    params: Mapping[str, Any],
    environ: Mapping[str, str],
) -> tuple[ServerSpec, list[str]]:
    """Plain dr: the block's snapshot with values from environ; the names it could not find."""
    env_names = list(params.get("env") or ())
    headers = dict(params.get("headers") or {})
    missing = [n for n in [*env_names, *headers.values()] if n not in environ]
    spec = ServerSpec(
        name=params["server"],
        transport=params["transport"],
        command=params.get("command"),
        args=tuple(params.get("args") or ()),
        env={n: environ[n] for n in env_names if n in environ},
        url=params.get("url"),
        headers={h: environ[v] for h, v in headers.items() if v in environ},
    )
    return spec, missing


def _session() -> "dict[str, Any] | None":
    """The SESSION a dr-acp worker installed in the package's own shim, if any."""
    try:
        # A stored copy reads the package's own module; the package's imports itself.
        from deep_reasoning.mcp import shim  # noqa: PLW0406
    except ImportError:
        return None
    return shim.SESSION


def mcp_server(client: Any, params: dict[str, Any]) -> Any:
    """The factory (§4.3): what dr-acp's worker connected (SESSION), or, anywhere else, a
    connection of its own from the block; a stand-in when it cannot be bound."""
    name = params["name"]
    session = _session()
    if session is not None:
        return session.get(name) or unavailable(name, NOT_IN_SESSION)
    try:
        import mcp  # noqa: F401
    except ImportError:
        return unavailable(name, NO_MCP_PACKAGE)
    spec, missing = spec_from_block(params, os.environ)
    connection = Connection(
        spec,
        name=name,
        errlog=sys.stderr,
        call_timeout_s=float(params.get("call_timeout_s", CALL_TIMEOUT_S)),
    )
    connection.start()
    seconds = float(params.get("connect_timeout_s", CONNECT_TIMEOUT_S))
    if connection.wait_ready(seconds) and connection.failure is None:
        return bound(name, connection, granted=None)
    if connection.failure is None:
        connection.abandon()
        reason = NO_ANSWER.format(seconds=seconds)
    else:
        reason = COULD_NOT_START.format(detail=connection.failure)
    if missing:
        reason += MISSING_ENV.format(names=", ".join(missing))
    import structlog

    structlog.get_logger(__name__).warning("mcp.unavailable", tool=name, reason=reason)
    return unavailable(name, reason)


def guard(argv: Sequence[str]) -> NoReturn:
    """python -I shim.py --guard -- COMMAND ARGS… (§4.6): run the command in this process
    group, and end the group when the process that started this one is gone."""
    parent = os.getppid()
    command = list(argv[1:] if argv[:1] == ["--"] else argv)
    server = subprocess.Popen(command)

    def watch() -> None:
        # The original parent, not pid 1: a subreaper may adopt this process instead.
        while os.getppid() == parent:
            time.sleep(GUARD_POLL_S)
        os.killpg(0, signal.SIGKILL)

    threading.Thread(target=watch, daemon=True).start()
    code = server.wait()
    sys.exit(code if code >= 0 else 128 - code)


if __name__ == "__main__" and sys.argv[1:2] == ["--guard"]:
    guard(sys.argv[2:])
